# -*- coding: utf-8 -*-
"""Assignment 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZznWNV24Sqs_MVnBlcjdnt3C3KFkuZJ_

*********************************ASSIGNMENT 1***********************************

Python Program for simple interest


Simple interest formula is given by: 

Simple Interest = (P x T x R)/100 

Where, P is the principal amount 

T is the time  

R is the rate.
"""

P=float(input('Enter Principal Amount:\n'))
T=float(input('Enter Time:\n'))
R=float(input('Enter Rate:\n'))
SI =(P * T * R)/100
print('Simple Interest:',SI)